var cities = [
	{ city: "London", country: "United Kingdom", index: 280 },
	{ city: "Geneva", country: "Switzerland", index: 259 },
	{ city: "New York City", country: "United States", index: 237 },
	{ city: "Singapore", country: "Singapore", index: 228 },
	{ city: "Paris", country: "France", index: 219 },
	{ city: "San Francisco", country: "United States", index: 218 },
	{ city: "Copenhagen", country: "Denmark", index: 217 },
	{ city: "Sydney", country: "Australia", index: 215 },
	{ city: "Hong Kong", country: "Hong Kong", index: 214 },
	{ city: "Brisbane", country: "Australia", index: 208 },
	{ city: "Stockholm", country: "Sweden", index: 204 },
	{ city: "Amsterdam", country: "Netherlands", index: 199 },
	{ city: "Tokyo", country: "Japan", index: 198 },
	{ city: "Washington D.C.", country: "United States", index: 197 },
	{ city: "Helsinki", country: "Finland", index: 192 },
	{ city: "Dublin", country: "Ireland", index: 191 },
	{ city: "Wellington", country: "New Zealand", index: 181 },
	{ city: "Munich", country: "Germany", index: 176 },
	{ city: "Toronto", country: "Canada", index: 175 },
	{ city: "Manchester", country: "United Kingdom", index: 175 },
	{ city: "Reykjavik", country: "Iceland", index: 173 },
	{ city: "Tel Aviv", country: "Israel", index: 173 },
	{ city: "Brussels", country: "Belgium", index: 171 },
	{ city: "Rome", country: "Italy", index: 169 },
	{ city: "Vancouver", country: "Canada", index: 167 },
	{ city: "Seattle", country: "United States", index: 166 },
	{ city: "Auckland", country: "New Zealand", index: 165 },
	{ city: "Hamburg", country: "Germany", index: 165 },
	{ city: "Doha", country: "Qatar", index: 164 },
	{ city: "Abu Dhabi", country: "United Arab Emirates", index: 164 },
	{ city: "Lagos", country: "Nigeria", index: 162 },
	{ city: "Los Angeles", country: "United States", index: 160 },
	{ city: "Vienna", country: "Austria", index: 159 },
	{ city: "Milan", country: "Italy", index: 158 },
	{ city: "Sacramento", country: "United States", index: 157 },
	{ city: "Moscow", country: "Russia", index: 157 },
	{ city: "Portland", country: "United States", index: 154 },
	{ city: "Newcastle", country: "United Kingdom", index: 154 },
	{ city: "Madrid", country: "Spain", index: 152 },
	{ city: "Montreal", country: "Canada", index: 151 },
	{ city: "Beirut", country: "Lebanon", index: 148 },
	{ city: "Baltimore", country: "United States", index: 145 },
	{ city: "Barcelona", country: "Spain", index: 143 },
	{ city: "Athens", country: "Greece", index: 143 },
	{ city: "São Paulo", country: "Brazil", index: 138 },
	{ city: "Lisbon", country: "Portugal", index: 128 },
	{ city: "Montevideo", country: "Uruguay", index: 128 },
	{ city: "Brasília", country: "Brazil", index: 123 },
	{ city: "San Antonio", country: "United States", index: 122 },
	{ city: "Santiago", country: "Chile", index: 121 },
	{ city: "Bogotá", country: "Colombia", index: 117 },
	{ city: "Riga", country: "Latvia", index: 115 },
	{ city: "Zagreb", country: "Croatia", index: 115 },
	{ city: "Johannesburg", country: "South Africa", index: 112 },
	{ city: "Kuala Lumpur", country: "Malaysia", index: 108 },
	{ city: "Mexico City", country: "Mexico", index: 105 },
	{ city: "Prague", country: "Czech Republic", index: 100 },
	{ city: "Nairobi", country: "Kenya", index: 99 },
	{ city: "Kraków", country: "Poland", index: 96 },
	{ city: "Kiev", country: "Ukraine", index: 94 },
	{ city: "Pretoria", country: "South Africa", index: 93 },
	{ city: "Bucharest", country: "Romania", index: 93 },
	{ city: "Jeddah", country: "Saudi Arabia", index: 89 },
	{ city: "Sofia", country: "Bulgaria", index: 88 },
	{ city: "Chiang Mai", country: "Thailand", index: 77 },
	{ city: "Brasov", country: "Romania", index: 77 },
	{ city: "Cairo", country: "Egypt", index: 76 },
	{ city: "Dhaka", country: "Bangladesh", index: 72 },
	{ city: "Delhi", country: "India", index: 57 },
	{ city: "Kolkata", country: "India", index: 40 },
];